### ISSUE TITLE
Implement server tests

### ISSUE THREAD

**Issue by doriengr** [green-ecolution/green-ecolution-backend#131]
- [ ] fileimport (Low priority because this is going to be moved to a plugin system)
- [ ] errorhandler
- [x] #174 
- [x] #162 
- [x] role (functionality not implemented yet - onhold)
- [x] #171 (only GetAllSensor currently implemented)
- [x] #169
- [x] #164 
- [x] #170
- [x] #176
